# Site settings
title: My GitHub Pages Site
description: This is my site description.
url: https://username.github.io

# Widget settings
widget_enabled: true
widget_title: My Widget
widget_code: >
  <div id="my-widget">
    <h2>This is my widget</h2>
    <p>Here is some content for my widget.</p>
  </div>

# Build settings
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
